version: "3.8"
services:
  app :
    build: ./code/
    depends_on: 
     db:
      condition: service_healthy
    volumes:
      - ./code/app.log:/code/app.log
  
  db:
    build: ./db/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 5s
      retries: 5