name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12.0


    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./software/code/requirements.txt  # Replace with the actual command to install your dependencies

    - name: Run tests
      run: |
        python -m unittest discover  # Replace with the actual command to run your tests
