CREATE TABLE tw_data (
    id SERIAL PRIMARY KEY, 
    "Loc" INT,
    "Loc Zn" VARCHAR(50),
    "Loc Name" VARCHAR(50),
    "Loc Purp Desc" VARCHAR(2) CHECK ("Loc Purp Desc" IN ('M2', 'MQ')),
    "Loc/QTI" VARCHAR(3) CHECK ("Loc/QTI" IN ('RPQ', 'DPQ')),
    "Flow Ind" VARCHAR(1) CHECK ("Flow Ind" IN ('R', 'D')),
    "DC" INTEGER,
    "OPC" INTEGER,
    "TSQ" INTEGER,
    "OAC" INTEGER,
    "IT" BOOLEAN,
    "Auth Overrun Ind" BOOLEAN,
    "Nom Cap Exceed Ind" BOOLEAN,
    "All Qty Avail" BOOLEAN,
    "Qty Reason" VARCHAR(200),
    "Date" DATE,
    "Cycle" VARCHAR(10) CHECK ("Cycle" IN ('Timely', 'Evening', 'Intraday 1','Intraday 2', 'Intraday 3', 'Final'))
);
